# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  #see https://github.com/LanceMcCarthy/DevReachCompanion/blob/master/azure-pipelines.yml
  major: '0'
  minor: '1'
  revision: $[counter(variables['minor'], 1)]
  App.Version: '$(major).$(minor).$(revision)'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
- task: VSBuild@1
  displayName: 'Build $(buildConfiguration)'
  inputs:
    solution: '**\*.sln'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AssemblyVersion:"$(App.Version)" /p:AssemblyFileVersion:"$(App.Version)" /p:Version:"$(App.Version)"'
    
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*tests*.dll
     !**\*TestAdapter.dll
     !**\obj\**
    runInParallel: true
    codeCoverageEnabled: true
    otherConsoleOptions: ' /Logger:"console"'
    failOnMinTestsNotRun: true
    diagnosticsEnabled: true
    publishRunAttachments: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
  
